version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
        - ./.env.db
    volumes:
       - postgres:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
        - ./.env.pgadmin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: